#!/bin/zsh

# Set the PGPASSFILE environment variable to the local .pgpass file
export PGPASSFILE="$(pwd)/.pgpass"

# Display the current value of PGPASSFILE
echo "Using PGPASSFILE: $PGPASSFILE"
psql -f "$(pwd)/sql/create_org_levels.sql" -U postgres
