#!/bin/zsh

# Get token and user_id
token=$(dev/scripts/get_token)
user_id=$(cat dev/scripts/user_id)
response=$(dev/scripts/create_project -n "test project" -d "hi i am a description" -u $user_id -t $token)
project_id=$(echo "$response" | jq -r '.id')
if [ -z "$project_id" ] || [ "$project_id" = "null" ]; then
  echo "$response"
else
  echo $project_id > dev/scripts/project_id
fi

