#!/bin/zsh

resp=$(dev/scripts/create_user -f dave -l hasseldorf -e "test2@email.com" -p hello)
user_id=$(echo $resp | jq -r ".id")
if [ -z "$user_id" ] || [ "$user_id" = "null" ]; then
    echo $resp
    exit 1
fi
echo "saving second user id $user_id"
echo $user_id > dev/scripts/second_user_id
