#!/bin/zsh

# Get token and user_id
token=$(dev/scripts/get_token)
user_id=$(cat dev/scripts/user_id)
project_id=$(cat dev/scripts/project_id)
api_key=$(cat dev/scripts/api_key)
response=$(dev/scripts/get_logs -p $project_id -u $user_id -t $token -a $api_key)
echo $response
