#!/bin/zsh

# Parse command-line flags
while getopts l:p:m:e:i:t:u:a:o:s:f: flag
do
    case "${flag}" in
        l) level_id="${OPTARG}";;
        p) project_id="${OPTARG}";;
        a) api_key="${OPTARG}";;
        m) message="${OPTARG}";;
        e) traceback="${OPTARG}";;
        i) process_id="${OPTARG}";;
        o) org_id="${OPTARG}";;
        u) user_id="${OPTARG}";;
        t) token="${OPTARG}";;
        s) date_start="${OPTARG}";;
        f) date_finish="${OPTARG}";;
        *) echo "Invalid flag"; exit 1;;
    esac
done

# Ensure all required flags are provided
if [ -z "${token}" ] || [ -z "${user_id}" ] ; then
    echo "Missing required flags: user_id or token"
    exit 1
fi

if [ "${message}" ]; then
    message=", \"message\": \"${message}\""
else
    message=""
fi

if [ "${process_id}" ]; then
    process_id=", \"process_id\": \"${process_id}\""
else
    process_id=""
fi

if [ "${traceback}" ]; then
    traceback=", \"traceback\": \"${traceback}\""
else
    traceback=""
fi
if [ "${org_id}" ]; then
    org_id=", \"org_id\": \"${org_id}\""
else
    org_id=""
fi
if [ "${level_id}" ]; then
    level_id=", \"level_id\": \"${level_id}\""
else
    level_id=""
fi
if [ "${project_id}" ]; then
    project_id=", \"project_id\": \"${project_id}\""
else
    project_id=""
fi
if [ "${date_start}" ]; then
    date_from=", \"from\": \"${date_start}\""
else
    date_from=""
fi

if [ "${date_finish}" ]; then
    date_to=", \"to\": \"${date_finish}\""
else
    date_to=""
fi

if [ -z "${message}" ] && [ -z "${process_id}" ] && [ -z "${traceback}" ] && [ -z "${org_id}" ] && [ -z "${level_id}" ] && [ -z "${project_id}" ] ; then
    data=""
else
    value="${message}${process_id}${traceback}${org_id}${level_id}${project_id}${date_from}${date_to}"
    value="${value:2}"
    data="{${value}}"
fi

# Send data using curl with interpolated variables
curl -X GET \
     -H "Content-Type: application/json" \
     -H "Accept: application/json" \
     -H "user_id: ${user_id}" \
     -H "api_key: ${api_key}" \
     -b "Authorization=${token}" \
     -d "${data}" \
     --no-progress-meter \
     localhost:8080/log
