#!/bin/zsh

echo "creating user"
dev/scripts/create_test_user
echo "creating second user"
dev/scripts/create_second_test_user
echo "authenticating user"
dev/scripts/authenticate_test_user
echo "testing authorization with token"
dev/scripts/authorize
echo "creating test project"
dev/scripts/create_test_project
echo "creating test api key"
dev/scripts/create_test_api_key
echo "creating test org"
dev/scripts/create_test_org
echo "inviting second user to test org"
dev/scripts/create_test_project_invite
